# Generated by Django 2.1.7 on 2019-03-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=100)),
                ('medValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medMaterial', models.CharField(max_length=100)),
                ('medFor', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('medManufactureCompany', models.CharField(max_length=100)),
            ],
        ),
    ]
